name: Backend - Django CI

on:
  push:
    paths:
      - "mi_proyecto/**"
      - "ghl_api/**"
      - "requirements.txt"
  pull_request:
    paths:
      - "mi_proyecto/**"
      - "ghl_api/**"
      - "requirements.txt"

jobs:
  django-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          cd mi_proyecto
          python manage.py migrate

      - name: Run Django tests
        run: |
          cd mi_proyecto
          python manage.py test

